<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Túi xách nữ kiểu 1',
                'slug' => 'tui-xach-nu-1',
                'thumbnail' => 'bag1.jpg',
                'content' => 'Mô tả chi tiết sản phẩm túi xách nữ 1',
                'description' => 'Túi xách nữ đẹp',
                'price_buy' => 500000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Túi xách nam kiểu 1',
                'slug' => 'tui-xach-nam-1',
                'thumbnail' => 'bag2.jpg',
                'content' => 'Mô tả chi tiết sản phẩm túi xách nam 1',
                'description' => 'Túi xách nam cao cấp',
                'price_buy' => 600000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            // ---- Thêm 10 sản phẩm mới ----
            [
                'category_id' => 1,
                'name' => 'Túi xách nữ thời trang 2',
                'slug' => 'tui-xach-nu-2',
                'thumbnail' => 'bag3.jpg',
                'content' => 'Mô tả chi tiết túi xách nữ thời trang 2',
                'description' => 'Túi xách nữ cao cấp thời trang',
                'price_buy' => 450000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Túi xách nữ da bò 3',
                'slug' => 'tui-xach-nu-3',
                'thumbnail' => 'bag4.jpg',
                'content' => 'Mô tả chi tiết túi xách nữ da bò 3',
                'description' => 'Túi xách nữ da thật',
                'price_buy' => 750000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Túi xách nữ đeo chéo 4',
                'slug' => 'tui-xach-nu-4',
                'thumbnail' => 'bag5.jpg',
                'content' => 'Mô tả chi tiết túi xách nữ đeo chéo',
                'description' => 'Túi xách đeo chéo tiện dụng',
                'price_buy' => 350000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Túi xách nữ dự tiệc 5',
                'slug' => 'tui-xach-nu-5',
                'thumbnail' => 'bag6.jpg',
                'content' => 'Mô tả chi tiết túi xách nữ dự tiệc',
                'description' => 'Túi xách sang trọng cho tiệc',
                'price_buy' => 820000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Túi xách nam công sở 2',
                'slug' => 'tui-xach-nam-2',
                'thumbnail' => 'bag7.jpg',
                'content' => 'Mô tả chi tiết túi xách nam công sở 2',
                'description' => 'Túi xách công sở tiện lợi',
                'price_buy' => 680000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Túi xách nam da thật 3',
                'slug' => 'tui-xach-nam-3',
                'thumbnail' => 'bag8.jpg',
                'content' => 'Mô tả chi tiết túi xách nam da thật',
                'description' => 'Túi xách da thật cao cấp',
                'price_buy' => 950000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Túi đeo chéo nam 4',
                'slug' => 'tui-deo-cheo-nam-4',
                'thumbnail' => 'bag9.jpg',
                'content' => 'Mô tả chi tiết túi đeo chéo nam',
                'description' => 'Túi đeo chéo gọn nhẹ',
                'price_buy' => 420000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Cặp xách laptop nam 5',
                'slug' => 'cap-laptop-nam-5',
                'thumbnail' => 'bag10.jpg',
                'content' => 'Mô tả chi tiết cặp xách laptop nam',
                'description' => 'Cặp laptop chống sốc cao cấp',
                'price_buy' => 1050000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Túi tote nữ 6',
                'slug' => 'tui-tote-nu-6',
                'thumbnail' => 'bag11.jpg',
                'content' => 'Mô tả túi tote nữ thời trang',
                'description' => 'Túi tote nữ tiện lợi',
                'price_buy' => 280000,
                'created_at' => now(),
                'created_by' => 1,
                'status' => 1,
            ],
        ]);
    }
}
